### ISSUE TITLE
Discrepancy between unicode-7.0.0\bidi character classes and respective Unicode date from ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt

### ISSUE THREAD

**Issue by ashensis** [mathiasbynens/node-unicode-data#22]
After comparing the character classes found in unicode-7.0.0\bidi\index.js and corresponding classification under Unicode official site ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt
I found multiple differences, like at points 13,44,46,48,134,174,666,667 etc.
What is the coorect data to rely upon?

**Comment by mathiasbynens** [comment]
<ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt> is the latest available Unicode version, which is 8.0.0 at the moment, not 7.0.0.

See https://github.com/mathiasbynens/node-unicode-data/blob/2ead4522aa1564e8c569189e7fe8ceaf3d7b99d7/data/resources.js#L165-L175 for which resources are used.

**Comment by ashensis** [comment]
Thanks a lot, my apologies
