### ISSUE TITLE
Make `bidi-classes/index.js` more compact

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/node-unicode-data#27]
Now that canonical names for bidi classes are being used, the size of `bidi-classes/index.js` increased drastically. E.g. `unicode-8.0.0/bidi-classes/index.js` is ~12.7 MB. 😨 

```
$ wc -c unicode-8.0.0/bidi-classes/index.js
 12707274 unicode-8.0.0/bidi-classes/index.js
```

Wanted: an npm module that minifies code like

```js
['long string', 'long string', 'long string']
```

…into something like…

```js
var a='long string';[a,a,a]
```

I feel like this probably already exists so I’ve asked here before building it myself: https://github.com/h5bp/lazyweb-requests/issues/193

**Comment by mathiasbynens** [comment]
Hmm, doing `var u=undefined;` and then using `u` instead of `undefined` yields ~7 MB savings.

**Comment by qfox** [comment]
Could use a parser, put all the strings in an array and do the leg work yourself. It shouldn't be too much work. An npm module for this is pretty specific.

**Comment by mathiasbynens** [comment]
Got the size down from 12.7 MB to 6.8 MB.

```
$ wc -c output/unicode-8.0.0/bidi-classes/index.js
 6804602 output/unicode-8.0.0/bidi-classes/index.js
```

**Comment by mathiasbynens** [comment]
Files that would benefit from minification of repeated string values (https://github.com/h5bp/lazyweb-requests/issues/193):

* `categories/index.js` (one entry for every code point from U+000000 to U+10FFFF)
* `bidi-classes/index.js` (limited number of entries, but lots of repeated strings)
* `bidi-brackets/index.js` (limited number of entries, but lots of repeated strings)

**Comment by mathiasbynens** [comment]
Moved the string deduping to another issue: #31
