### ISSUE TITLE
require('unicode-x.x.x/categories') not works

### ISSUE THREAD

**Issue by hakatashi** [mathiasbynens/node-unicode-data#35]
It seems that unicode-x.x.x/categories/index.js has been removed from the packages and `require('unicode-x.x.x/categories')` is unavailable since 0.5.0.

Is this an intentional change? Are there any replacement for this feature? (I just want to iterate through all characters in Unicode and get the corresponding categories)

**Comment by mathiasbynens** [comment]
Whoops, seems like it was removed recently: https://github.com/mathiasbynens/unicode-8.0.0/commit/13e0e939c476519afb94066af95619737da11b90#diff-16249c9230c551eb7f9c5111bb5c5a66 (output diff)

A recent commit to https://github.com/mathiasbynens/node-unicode-data/commits/master must be the culprit. I can take a look after the weekend. For now you can use an older version of `unicode-8.0.0`.

**Comment by hakatashi** [comment]
Thanks for the fix!
