### ISSUE TITLE
Why shouldn't generated packages be used a regular dependency?

### ISSUE THREAD

**Issue by pdubroy** [mathiasbynens/node-unicode-data#43]
First of all, thanks a lot for these packages!

In the README files, you say:

> Note: unicode-9.0.0 is supposed to be used in build scripts (i.e. as a devDependency), and not at runtime (i.e. as a regular dependency).

Could you clarify the reason behind this? It's not obvious to me why we shouldn't add these packages as a regular dependency. If there's a good reason, maybe it's worth adding a short note to the README as well (and I'd be happy to submit a PR).

**Comment by mathiasbynens** [comment]
Loading the data at run-time can be quite slow, especially for large arrays.

What is your use case for wanting to use the packages at run-time?

**Comment by pdubroy** [comment]
It's for Ohm, a parser generator for JavaScript: https://github.com/harc/ohm/. We have a built-in `letter` rule that is supposed to match anything in one of the Unicode letter categories. We were maintaining our own module with regular expressions for the various categories (https://github.com/harc/ohm/blob/master/third_party/UnicodeCategories.js), but we'd like to depend on one of your packages instead.

We would just be requiring the regex modules, and those all seem to load quite fast. Or is there an issue that I'm missing?

**Comment by mathiasbynens** [comment]
It would work, sure, but having e.g. unicode-9.0.0 as a `dependency` would slow down installation times for consumers of your library.

Did you see https://github.com/mathiasbynens/unicode-9.0.0#regular-expressions?

Specifically for ECMAScript identifier matching (which I assume is why you used Letter for ES5), you might be interested in https://gist.github.com/mathiasbynens/6334847.

**Comment by pdubroy** [comment]
Gotcha, thanks.

And thanks for the pointer to your article on ES5 identifiers...that is indeed useful!

**Comment by mathiasbynens** [comment]
I’m gonna close this, but happy to discuss further!

Also, feel free to CC me on any related Ohm issues.
