### ISSUE TITLE
FYI: es-identifiers

### ISSUE THREAD

**Issue by brettz9** [mathiasbynens/node-unicode-data#46]
Thanks for all the really great Unicode tools, Mathias.

Just letting you know I've added a simple derivative library, https://github.com/brettz9/es-identifiers for the ES `IdentifierName` production. We needed it in IndexedDBShim, and I need it in another project, so thought I'd release.

**Comment by mathiasbynens** [comment]
Nice!

I noted that you’re using `…/regex.js` and then using the `.source` property, which feels a little hacky to me. As your comment states, Regenerate could be used directly instead. The comment hints that this is complicated but all you need is these few lines: https://gist.github.com/mathiasbynens/6334847#file-javascript-identifier-regex-js-L69-L86 Anyway, it’s up to you :)

FYI, esutils has utility methods for `isIdentifierStart` and `isIdentifierPart` too: https://github.com/estools/esutils#codeisidentifierstartcode

**Comment by brettz9** [comment]
I see I'll need to reuse all of the specific hex code point values...I think I hadn't noticed your interface supports passing in string ranges as well as numeric ones, so yeah, I think using your code would be best.

But as I'd like to support the full expression, some extra code beyond that in your Gist is needed for (more fine-tuned) escape sequences (as you may have gathered by your post at https://github.com/brettz9/es-identifiers/issues/1), so it's not quite that simple unfortunately. (While a utility function, as in `estools` offers the advantage of being more succinct, I'd like to inject a regex into `<input pattern>` without need for further (client-side) JavaScript validation.)
