### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [mathiasbynens/node-unicode-data#47]
I think I could use that to generate quite a few Debian packages for unicode in Node.js -- if only there were releases :-P

Could you tag releases, please?

Thanks!

**Comment by mathiasbynens** [comment]
This repo is just the build script. I don’t want to bother with cutting releases for it.

The list of generated packages can be found here: https://github.com/mathiasbynens/node-unicode-data#using-the-data-in-your-scripts They’re tagged and released and I imagine these packages are what you’re after.

**Comment by SnarkBoojum** [comment]
Well, I need the source code for the packages...

Let's see if I understand well: unicode-10.0.0 is half-generated and half-written?

**Comment by mathiasbynens** [comment]
It’s 100% generated by the script in this repo.
