### ISSUE TITLE
unicode-10.0.0 has a Block named "undefined"

### ISSUE THREAD

**Issue by josephfrazier** [mathiasbynens/node-unicode-data#50]
From https://github.com/slevithan/xregexp/pull/221#pullrequestreview-97394129

```js
require('unicode-10.0.0').Block[273]
// -> 'undefined'
```

**Comment by josephfrazier** [comment]
I looked into this a bit, and found that at [this line](https://github.com/mathiasbynens/node-unicode-data/blob/ec560982893ec61e5b1363a1fa5578727270eea4/scripts/parse-blocks-scripts-properties.js#L51) in `parseBlocks` `unicode-loose-match` seems to be unable to handle an `item` argument of `"Syriac_Supplement"`. I'll probably open an issue there.

**Comment by mathiasbynens** [comment]
This should be fixed now.

**Comment by josephfrazier** [comment]
Thanks! Has there been a `unicode-10.0.0` release with the fix? I don't see it on npm

**Comment by mathiasbynens** [comment]
Good catch! unicode-10.0.0@0.7.5 is now up.

**Comment by josephfrazier** [comment]
Cheers!
