### ISSUE TITLE
If there are only 32k unicode characters currently

### ISSUE THREAD

**Issue by ruscandino** [mathiasbynens/node-unicode-data#55]
I just loaded [this](https://github.com/mathiasbynens/node-unicode-data/blob/master/data/12.1.0-database.txt) and there was only about ~32k characters in there, but the unicode standard has room for over a million. Wondering if this is the correct character count, or if I am supposed to be getting them from some other places as well.

**Comment by mathiasbynens** [comment]
Unicode ranges from U+000000 to U+10FFFF but most of these code points are not currently assigned. See the `Assigned` and `Unassigned` properties.
